server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://dpg-cpisnd4f7o1s73bmbcjg-a/trocaaqui
        username: portgress
        password: SyT8ey3YHDHdu496UcOJtjEu2trXpA6T
        driver-class-name: org.postgresql.Driver
        initialize: true

    jpa: 
        hibernate:
            ddl-auto: create-drop
            generate-ddl: true

    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres
